
import fetch from 'node-fetch';

const response = await fetch('https://app.rs.school/');

// Returns an array of values, instead of a string of comma-separated values
console.log(response.headers.raw()['auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDk1OTQsImlzQWRtaW4iOmZhbHNlLCJpc0hpcmVyIjpmYWxzZSwiZ2l0aHViSWQiOiJ6aWJlcnBheCIsImFwcFJvbGVzIjpbInVzZXIiXSwicm9sZXMiOnsiNTgiOiJzdHVkZW50IiwiNjEiOiJzdHVkZW50IiwiNjQiOiJzdHVkZW50IiwiNjgiOiJzdHVkZW50In0sImNvdXJzZXMiOnsiNTgiOnsicm9sZXMiOlsic3R1ZGVudCJdLCJzdHVkZW50SWQiOjc4Mzk1LCJpc0V4cGVsbGVkIjp0cnVlfSwiNjEiOnsicm9sZXMiOlsic3R1ZGVudCJdLCJzdHVkZW50SWQiOjg2MzcxLCJpc0V4cGVsbGVkIjpmYWxzZX0sIjY0Ijp7InJvbGVzIjpbInN0dWRlbnQiXSwic3R1ZGVudElkIjo4NjM3NCwiaXNFeHBlbGxlZCI6ZmFsc2V9LCI2OCI6eyJyb2xlcyI6WyJzdHVkZW50Il0sInN0dWRlbnRJZCI6OTY3MjYsImlzRXhwZWxsZWQiOmZhbHNlfX0sImlhdCI6MTY2ODM2NDAwOCwiZXhwIjoxNjY4NTM2ODA4fQ.6fzdJZQcZ_MA1AAfWtE04JBZqJmAm2wkY4nZ4hmwd1g']);